### ISSUE TITLE
Application Do not open .

### ISSUE THREAD

**Issue by zarqizoubir** [colinlienard/gitlight#149]
Hello .
I have an issue after installing the application on my linux system `.deb` .
the bin I installed is `git-light_0.11.1_amd64.deb`.

after the installation done , the application wouldn't open, and when trying to open the app from the terminal and it log something like this :
`git-light: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

#### OS :
```
OS: Pop!_OS 22.04 LTS x86_64
Host: 82C6 Lenovo V14-ADA
Kernel: 6.2.6-76060206-generic
Shell: bash 5.1.16
```
#### CPU :
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  Byte Order:            Little Endian
```

**Comment by colinlienard** [comment]
Thanks for reporting this!

Seems like it's caused by Ubuntu switching from openssl v1 to v3 as explained here: https://github.com/tauri-apps/tauri/issues/4470#issuecomment-1170342732

This problem occurs because Gitlight uses the tauri updater, but the updater only works for `.AppImage` (https://tauri.app/v1/guides/distribution/updater/), could you please try installing the `.AppImage` bundle?

**Comment by zarqizoubir** [comment]
Oh yeah after installing the `.AppImage` version it work fine .
thanks @colinlienard .
