### ISSUE TITLE
Tray icon invible in macos dark mode

### ISSUE THREAD

**Issue by bbannier** [colinlienard/gitlight#255]
I have set my system theme to dark mode which sets the background color of the system tray to a very light gray. Since the `tray-base.png` is white without new notifications the tray icon is basically invisible unless clicked (in fact I only noticed that there was even a tray icon since I had new notifications).

<img width="94" alt="Tray icon without notifications" src="https://github.com/colinlienard/gitlight/assets/324957/b17cbc16-e585-4b56-aa2e-1b963d7eea97">

<img width="62" alt="Tray icon with notifications" src="https://github.com/colinlienard/gitlight/assets/324957/94b60438-97f5-4243-8ff7-7b1ac29589ef">

<img width="53" alt="Tray icon clicked" src="https://github.com/colinlienard/gitlight/assets/324957/5ee3e6bd-71e5-49c8-9060-9434886f2bd4">

It would be great if gitlight would either provide dedicated icons for dark mode, or if that is [impossible with the used tauri-1.*](https://github.com/tauri-apps/tauri/issues/6645) switch the icons to use something which works reasonably well against both a light and a dark background.

**Comment by colinlienard** [comment]
Thanks for your feedback!

I think this problem is more about the wallpaper than the os theme, for example here I set a light wallpaper but I'm still in dark mode:

<img width="292" alt="image" src="https://github.com/colinlienard/gitlight/assets/64312634/79899d17-88e8-48d2-bb49-b85964139c9f">

The solution is probably about template icon (https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc%5C), I'll look into it

**Comment by bbannier** [comment]
Ah you are right. The tray seems to be (at least partially) transparent and my whitish background images shines through.
