### ISSUE TITLE
Add support for WorkflowRun notifications

### ISSUE THREAD

**Issue by colinlienard** [colinlienard/gitlight#88]
Encountered here: https://github.com/colinlienard/gitlight/issues/66

Don't know yet how to repro this type of notification

**Comment by Hacksore** [comment]
I have a few repos that might be helpful here.

https://github.com/Hacksore/github-websocket-api
https://github.com/Hacksore/github-websocket-pipeline-api

A while back I was working on https://buildtray.com but scrapped it and just used webhooks/discord 😂.

This definitely would be an awesome feature and if it could be pulled off id for sure use it.

**Comment by Hacksore** [comment]
Yeah but that’s clutters up your desktop experience 😅.

Those apis I listed are unofficial but they are realtime and don’t require anything to be configured.

When I asked @Github to support backgrounding their desktop app they said no because of some silly “windows design guidelines” 😡

https://github.com/desktop/desktop/issues/17587

**Comment by Hacksore** [comment]
also there was this issue too and the official vscode extensio long polls too 😅.

https://github.com/cschleiden/vscode-github-actions/issues/5 (old verson and it was moved to [github/vscode-github-actions](https://github.com/github/vscode-github-actions))
