### ISSUE TITLE
Set notifications to "done"

### ISSUE THREAD

**Issue by maku** [colinlienard/gitlight#95]
I do not see an option to set the "notifications" to done. Is this possible?

**Comment by colinlienard** [comment]
Don't you have the purple button with a tick in it when you hover over a notification? 

![image](https://github.com/colinlienard/gitlight/assets/64312634/5a9360f5-1b56-486a-8011-0ca049c0c58d)

**Comment by maku** [comment]
In github notifications I have a "Done" button -> so that notifications "go away" when I am done. 

![2023-06-13 10_35_17-Notifications](https://github.com/colinlienard/gitlight/assets/64805/bed28c62-7042-4e71-99c4-55ff3c04bccd)

This is what I mean....

In gitlight UI, I only find the option to set the "read" flag

**Comment by colinlienard** [comment]
Oh ok I understand
Basically this just removes notifications from the ui and currently there is no way to do the same thing in GitLight, would you find this useful? Does the read flag seem "not enough" to you?

**Comment by colinlienard** [comment]
Maybe an option to hide the "Read" column would be enough? Or do you really want to distinguish between "read" and "done" notifications?

**Comment by maku** [comment]
@colinlienard no worries, I think the workflow which is implemented in gitlight is fine. But the tool is not the right coice for my style of working with github notifications. Nevertheless thank you for building a great tool.

**Comment by tefkah** [comment]
Just to chime in: I'd also like this feature! My main usecase is that while the "read" column is not very distracting in GitLight, occassionally I'll probably still open the Github notifications tab, where "Read" notifications hide the "Unread" ones in the "all" view.

How I usually use notifications is that "Unread" is Unread, Read is "Currently being handled", and "Done" is done, not to be looked at again.

Also, I notice that GitLight "only" seems to sync up to 50 notifications.  Since there's no way to dismiss the read notifications, I feel like there isn't a way to prompt gitlight to fetch more. Although even if I dismiss them in GitHub GitLight does not seem to fetch more older ones, so maybe this is by design

**Comment by colinlienard** [comment]
Thanks really appreciate it!

Your way of using notifications is one I hadn't thought of, but there are probably others who do it the same way, so I think I should definitely implement a solution. Maybe a way to select notifications and "delete" them would be nice, as well as a space where deleted notifications could be found in case they were accidentally deleted.

For the limitation to 50 notifications, someone also mentioned that this is sometimes not enough so I'm planning on adding a setting to maybe increase it to 100 (#116). But to get GitHub notifications, I fetch all of the latest ones whether read or not, and I don't think there is any other way to do it that would work for GitLight
