### ISSUE TITLE
Refine GitHub Permissions

### ISSUE THREAD

**Issue by lorenzolewis** [colinlienard/gitlight#96]
Right now using this requires granting permission read and write permission to both private and public repos. Is this required and if not would it be possible to restrict it down for this app?

**Comment by colinlienard** [comment]
Unfortunately it is required for GitLight to ask read and write permissions because the `repo` scope is needed in order to provide precise data. Without it, notifications would be the same as in the GitHub notifications page (not that good). And there is no scope that only ask for read permissions, which would be great because I don't write anything

**Comment by colinlienard** [comment]
Just discovered [fine-grained personal access tokens](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/), I'll try to integrate them
